import Link from 'next/link';
import { Wind, ArrowLeft, Shield } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50 selection:bg-emerald-100 selection:text-emerald-900 pb-20 pt-12">
      {/* Main Content */}
      <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        
        <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-slate-900 transition-colors text-sm font-bold mb-6 group">
          <div className="p-2 bg-white rounded-full border border-slate-200 shadow-sm group-hover:bg-slate-100 transition-colors">
            <ArrowLeft className="w-4 h-4" />
          </div>
          Back to Home
        </Link>

        <div className="bg-white rounded-[2.5rem] shadow-xl shadow-slate-200/40 border border-slate-100 overflow-hidden">
          
          <div className="bg-slate-900 px-8 py-12 sm:px-14 sm:py-16 text-center relative overflow-hidden">
             <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500/20 rounded-full filter blur-[100px] animate-pulse"></div>
             <div className="absolute bottom-0 left-0 w-64 h-64 bg-emerald-500/20 rounded-full filter blur-[100px] animate-pulse" style={{ animationDelay: '1.5s' }}></div>
             <div className="flex justify-center mb-6 relative z-10">
               <div className="w-16 h-16 bg-slate-800 rounded-2xl flex items-center justify-center border border-slate-700 shadow-lg">
                 <Shield className="w-8 h-8 text-emerald-400" />
               </div>
             </div>
             <h1 className="text-3xl sm:text-4xl font-extrabold text-white mb-4 tracking-tight relative z-10">
               Terms of Service
             </h1>
             <p className="text-sm text-emerald-100/60 font-bold relative z-10 tracking-widest uppercase">
               Last updated: October 2026
             </p>
          </div>

          <div className="p-8 sm:p-14 space-y-8 text-slate-600 text-base leading-relaxed">
            
            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing and using DHUAN (the "Platform"), you accept and agree to be bound by the terms and provision of this agreement. In addition, when using these particular services, you shall be subject to any posted guidelines or rules applicable to such services.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">2. Description of Service</h2>
              <p>
                DHUAN provides AI-powered smog intelligence, health advisories, and smart navigation specifically designed for the city of Lahore. We use Machine Learning (Random Forest & LSTM) to provide real-time air quality forecasts and routing features.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">3. Medical and Navigational Disclaimer</h2>
              <p className="p-4 bg-orange-50 border border-orange-100 rounded-xl text-orange-800 font-medium">
                <strong>Important:</strong> The health advisories generated by DHUAN's AI are for informational purposes only and do not constitute professional medical advice. Always consult a physician for health-related decisions. Furthermore, our smart navigation routes are generated dynamically based on AQI and traffic; please follow actual road signs and traffic laws.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">4. User Accounts</h2>
              <p>
                To use certain features (like personalized health insights), you must register for an account. You agree to provide accurate information and keep it updated. You are responsible for maintaining the confidentiality of your account and password.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">5. Data Privacy</h2>
              <p>
                Your privacy is critical to us. Please review our <Link href="/privacy" className="text-emerald-600 font-bold hover:underline">Privacy Policy</Link>, which also governs your use of DHUAN, to understand our practices regarding your personal, location, and health data.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">6. Modifications to Service</h2>
              <p>
                We reserve the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. You agree that DHUAN shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.
              </p>
            </section>

          </div>
        </div>
      </main>
    </div>
  );
}
